bpmn-beta LR
  start StartEvent_StartEvent "StartEvent"
  end EndEvent_EndEvent "EndEvent"
  subprocess n_6_185665 "SubProcess"
  n_6_185665 -- d --> EndEvent_EndEvent
  StartEvent_StartEvent -- a --> n_6_185665
