c4-beta container
title Tag Styles - Shapes and Colours

style database shape:cylinder
style async line:dashed
style team-a fill:#1F2937, stroke:#111827

container api "API Application" "Provides a JSON/HTTPS API." "Java/Spring MVC" :::team-a
container db "Database" "Stores user credentials." "Oracle 12c" :::database

api --> db : "Reads from and writes to" "SQL/TCP" :::async
